export const LOADING_STATUS = 'LOADING_STATUS';
export const OPERATE_SUCCESS = 'OPERATE_SUCCESS';
export const OPERATE_FAILED = 'OPERATE_FAILED';

export const FLOWLIST_REQUEST = 'FLOWLIST_REQUEST';
export const FLOWLIST_LIST = 'FLOWLIST_LIST';
export const FLOWLIST_ADD = 'FLOWLIST_ADD';
export const FLOWLIST_SHOW = 'FLOWLIST_SHOW';
export const FLOWLIST_EDIT = 'FLOWLIST_EDIT';
export const FLOWLIST_DELETE = 'FLOWLIST_DELETE';
export const FLOWLIST_GITMODEL = 'FLOWLIST_GITMODEL';
export const FLOWLIST_LOCALMODEL = 'FLOWLIST_LOCALMODEL';

export const PROJECTLIST_REQUEST = 'PROJECTLIST_REQUEST';
export const PROJECTLIST_LIST = 'PROJECTLIST_LIST';
export const PROJECTLIST_ADD = 'PROJECTLIST_ADD';
export const PROJECTLIST_SHOW = 'PROJECTLIST_SHOW';
export const PROJECTLIST_EDIT = 'PROJECTLIST_EDIT';
export const PROJECTLIST_DELETE = 'PROJECTLIST_DELETE';
export const PROJECTLIST_GITMODEL = 'PROJECTLIST_GITMODEL';
export const PROJECTLIST_LOCALMODEL = 'PROJECTLIST_LOCALMODEL';
