export const LOADING_STATUS = 'LOADING_STATUS';
export const OPERATE_SUCCESS = 'OPERATE_SUCCESS';
export const OPERATE_FAILED = 'OPERATE_FAILED';

export const FLOWLIST_REQUEST = 'FLOWLIST_REQUEST';
export const FLOWLIST_LIST = 'FLOWLIST_LIST';
export const FLOWLIST_ADD = 'FLOWLIST_ADD';
export const FLOWLIST_SHOW = 'FLOWLIST_SHOW';
export const FLOWLIST_EDIT = 'FLOWLIST_EDIT';
export const FLOWLIST_DELETE = 'FLOWLIST_DELETE';
export const FLOWLIST_GITMODEL = 'FLOWLIST_GITMODEL';
export const FLOWLIST_LOCALMODEL = 'FLOWLIST_LOCALMODEL';
